select * from customer limit 30;

-- total revenue generated by customers

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- used discount but still spent more than avg purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount) from customer)

-- top 5 products with highest review rating

select item_purchased, Round(avg(review_rating::numeric),2) as average_product_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- avg purchase amount between standard and express shipping

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- subscribers and non subscribers.

select subscription_status,
Count(customer_id) as Total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status

-- highest % of purchases with discount applied 

select item_purchased,
round(
		100 * Sum(case when discount_applied = 'Yes' then 1 else 0 end)/count (*),2
) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- new, returning and loyal customers based on total number of previous purchases

with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment
order by number_of_customers desc

-- top 3 purchased products within each category

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- repeat buyers and also likely to subscribers

select subscription_status,
count(customer_id)
from customer
where previous_purchases > 5
group by subscription_status


-- revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc